business_problems = {
    "supermarket chain": ["High operating costs", "Competition from other supermarkets", "Supply chain disruptions", "Declining sales"],
    "women's clothing boutique": ["Fashion trends that are out of style", "High cost of inventory", "Difficulty attracting customers", "Changing consumer preferences"],
    "hair salon and spa": ["Difficulty retaining employees", "Competition from other salons", "Increasing cost of supplies", "Declining customer demand"],
    "online banking": ["Security breaches", "Technical issues", "Competition from other online banks", "Regulatory compliance"],
    "italian restaurant": ["High cost of ingredients", "Difficulty retaining staff", "Competition from other restaurants", "Seasonal fluctuations in demand"],
    "dental clinic": ["Increasing cost of supplies", "Difficulty attracting patients", "Competition from other dental clinics", "Regulatory compliance"],
    "convenience store": ["High operating costs", "Competition from other convenience stores", "Shrinking profit margins", "Difficulty attracting customers"],
    "children's clothing store": ["Rapidly changing fashion trends", "High cost of inventory", "Seasonal fluctuations in demand", "Difficulty attracting customers"],
    "hair and makeup salon": ["Difficulty retaining employees", "Increasing cost of supplies", "Competition from other salons", "Declining customer demand"],
    "commercial bank": ["Competition from other banks", "Regulatory compliance", "Economic downturns", "Declining interest rates"],
    "fast food restaurant": ["High operating costs", "Increasing competition", "Changing consumer preferences", "Difficulty retaining employees"],
    "veterinary clinic": ["Increasing cost of supplies", "Difficulty attracting clients", "Competition from other clinics", "Regulatory compliance"],
    "department store": ["High operating costs", "Competition from other department stores", "Declining sales", "Changing consumer preferences"],
    "men's clothing store": ["Changing fashion trends", "High cost of inventory", "Difficulty attracting customers", "Seasonal fluctuations in demand"],
    "barber shop": ["Difficulty retaining employees", "Increasing cost of supplies", "Competition from other barber shops", "Declining customer demand"],
    "credit union": ["Competition from other banks", "Regulatory compliance", "Economic downturns", "Declining interest rates"],
    "chinese restaurant": ["High cost of ingredients", "Difficulty retaining staff", "Competition from other restaurants", "Seasonal fluctuations in demand"],
    "pediatric clinic": ["Increasing cost of supplies", "Difficulty attracting patients", "Competition from other clinics", "Regulatory compliance"],
    "thrift store": ["Difficulty attracting customers", "Changing consumer preferences", "High cost of inventory", "Competition from other thrift stores"],
    "nail salon and spa": ["Difficulty retaining employees", "Increasing cost of supplies", "Competition from other salons", "Declining customer demand"]
}
business_benefits = {
    "supermarket chain": ["Large customer base", "Stable demand for products", "Opportunities for growth and expansion", "Multiple revenue streams"],
    "women's clothing boutique": ["Opportunities to sell unique, high-quality products", "Ability to build a loyal customer base", "Opportunities for growth and expansion", "Flexibility in product offerings"],
    "hair salon and spa": ["Opportunities for repeat business", "Opportunities for growth and expansion", "Opportunities to offer a wide range of services", "Opportunities to build a loyal customer base"],
    "online banking": ["Convenience for customers", "Opportunities for growth and expansion", "Lower operating costs", "Opportunities for innovation"],
    "italian restaurant": ["Opportunities for repeat business", "Opportunities to offer a wide range of menu items", "Opportunities to build a loyal customer base", "Opportunities for growth and expansion"],
    "dental clinic": ["Stable demand for services", "Opportunities to build a loyal customer base", "Opportunities for growth and expansion", "Opportunities to offer a wide range of services"],
    "convenience store": ["Convenience for customers", "Opportunities to offer a wide range of products", "Stable demand for products", "Opportunities for growth and expansion"],
    "children's clothing store": ["Opportunities to sell unique, high-quality products", "Stable demand for children's clothing", "Opportunities for growth and expansion", "Opportunities to build a loyal customer base"],
    "hair and makeup salon": ["Opportunities for repeat business", "Opportunities to offer a wide range of services", "Opportunities to build a loyal customer base", "Opportunities for growth and expansion"],
    "commercial bank": ["Stable demand for financial services", "Opportunities for growth and expansion", "Multiple revenue streams", "Opportunities to build a loyal customer base"],
    "fast food restaurant": ["Stable demand for food", "Opportunities for growth and expansion", "Opportunities to offer a wide range of menu items", "Opportunities for repeat business"],
    "veterinary clinic": ["Stable demand for pet care services", "Opportunities to build a loyal customer base", "Opportunities for growth and expansion", "Opportunities to offer a wide range of services"],
    "department store": ["Opportunities to offer a wide range of products", "Stable demand for products", "Opportunities for growth and expansion", "Opportunities to build a loyal customer base"],
    "men's clothing store": ["Opportunities to sell unique, high-quality products", "Stable demand for men's clothing", "Opportunities for growth and expansion", "Opportunities to build a loyal customer base"],
    "barber shop": ["Opportunities for repeat business", "Opportunities to offer a wide range of services", "Opportunities to build a loyal customer base", "Opportunities for growth and expansion"],
    "credit union
